services:
    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - "443:443"
        networks:
            - ft_transcendence
        depends_on:
            - user_manager
        restart: always
    user_manager:
        container_name: user_manager
        build: ./user_manager
        volumes:
            - user_manager_db_volume:/database:rw
        networks:
            - ft_transcendence
        restart: always

networks:
    ft_transcendence:
        name: inception
        driver: bridge

volumes:
    user_manager_db_volume:
        name: user_manager_db_volume
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/msitni/data/user_manager_db_volume'
