services:
    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - "443:443"
        networks:
            - ft_transcendence
        depends_on:
            - api_gateway
        restart: always
    rabbitmq:
        container_name: rabbitmq
        build:
            context: ./rabbitmq
            args:
                RABBITMQ_NODENAME: ${RABBITMQ_NODENAME}
                RABBITMQ_API_GATEWAY_USER: ${RABBITMQ_API_GATEWAY_USER}  
                RABBITMQ_API_GATEWAY_PASSWORD: ${RABBITMQ_API_GATEWAY_PASSWORD}  
                RABBITMQ_USER_MANAGER_USER: ${RABBITMQ_USER_MANAGER_USER}  
                RABBITMQ_USER_MANAGER_PASSWORD: ${RABBITMQ_USER_MANAGER_PASSWORD}  
        volumes:
            - rabbit_mq_log_volume:/var/log/rabbitmq:rw
        networks:
            - ft_transcendence
        env_file: .env        
        init: true
        restart: always
    api_gateway:
        container_name: api_gateway
        build: ./micro_services/api_gateway
        volumes:
            - api_gateway_db_volume:/database:rw
        networks:
            - ft_transcendence
        depends_on:
            - rabbitmq
        restart: always
    user_manager:
        container_name: user_manager
        build: ./micro_services/user_manager
        volumes:
            - user_manager_db_volume:/database:rw
        networks:
            - ft_transcendence
        depends_on:
            - rabbitmq
        restart: always

networks:
    ft_transcendence:
        name: inception
        driver: bridge

volumes:
    api_gateway_db_volume:
        name: api_gateway_db_volume
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/msitni/data/api_gateway_db_volume'
    user_manager_db_volume:
        name: user_manager_db_volume
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/msitni/data/user_manager_db_volume'
    rabbit_mq_log_volume:
        name: rabbit_mq_log_volume
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/msitni/data/rabbit_mq_log_volume'
