services:
    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - "443:443"
        networks:
            - ft_transcendence
        depends_on:
            - api_gateway
        restart: always
    rabbitmq:
        container_name: rabbitmq
        build: ./rabbitmq
        volumes:
            - rabbit_mq_data_volume:/var/lib/rabbitmq/mnesia:rw
            - rabbit_mq_log_volume:/var/log/rabbitmq:rw
        networks:
            - ft_transcendence
        env_file: .env        
        restart: always
    api_gateway:
        container_name: api_gateway
        build: ./api_gateway
        volumes:
            - api_gateway_db_volume:/database:rw
        networks:
            - ft_transcendence
        depends_on:
            - rabbitmq
        restart: always

networks:
    ft_transcendence:
        name: inception
        driver: bridge

volumes:
    api_gateway_db_volume:
        name: api_gateway_db_volume
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/msitni/data/api_gateway_db_volume'
    rabbit_mq_data_volume:
        name: rabbit_mq_data_volume
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/msitni/data/rabbit_mq_data_volume'
    rabbit_mq_log_volume:
        name: rabbit_mq_log_volume
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/msitni/data/rabbit_mq_log_volume'
