services:
    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - "443:443"
        networks:
            - ft_transcendence
        depends_on:
            - api_gateway
        restart: always
    api_gateway:
        container_name: api_gateway
        build: ./api_gateway
        volumes:
            - api_gateway_db_volume:/database:rw
        networks:
            - ft_transcendence
        restart: always

networks:
    ft_transcendence:
        name: inception
        driver: bridge

volumes:
    api_gateway_db_volume:
        name: api_gateway_db_volume
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/msitni/data/api_gateway_db_volume'
