services:
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - static_data_volume:/api/static:ro
    ports:
      - "443:443"
    networks:
      - ft_transcendence
    restart: always
  vault:
    container_name: vault
    build: vault
    volumes:
      - vault_storage:/vault_storage:rw
    networks:
      - ft_transcendence
    restart: always
  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./rabbitmq
      args:
        RABBITMQ_HOST: ${RABBITMQ_HOST}
        RABBITMQ_PORT: ${RABBITMQ_PORT}
        RABBITMQ_NODENAME: ${RABBITMQ_NODENAME}
        RABBITMQ_API_GATEWAY_USER: ${RABBITMQ_API_GATEWAY_USER}
        RABBITMQ_API_GATEWAY_PASSWORD: ${RABBITMQ_API_GATEWAY_PASSWORD}
        RABBITMQ_USER_MANAGER_USER: ${RABBITMQ_USER_MANAGER_USER}
        RABBITMQ_USER_MANAGER_PASSWORD: ${RABBITMQ_USER_MANAGER_PASSWORD}
        RABBITMQ_FRIENDS_MANAGER_USER: ${RABBITMQ_FRIENDS_MANAGER_USER}
        RABBITMQ_FRIENDS_MANAGER_PASSWORD: ${RABBITMQ_FRIENDS_MANAGER_PASSWORD}
        RABBITMQ_NOTIFICATIONS_USER: ${RABBITMQ_NOTIFICATIONS_USER}
        RABBITMQ_NOTIFICATIONS_PASSWORD: ${RABBITMQ_NOTIFICATIONS_PASSWORD}
        RABBITMQ_LEADERBOARD_USER: ${RABBITMQ_LEADERBOARD_USER}
        RABBITMQ_LEADERBOARD_PASSWORD: ${RABBITMQ_LEADERBOARD_PASSWORD}
        RABBITMQ_MATCH_MANAGER_USER: ${RABBITMQ_MATCH_MANAGER_USER}
        RABBITMQ_MATCH_MANAGER_PASSWORD: ${RABBITMQ_MATCH_MANAGER_PASSWORD}
    volumes:
      - rabbit_mq_log_volume:/var/log/rabbitmq:rw
    networks:
      - ft_transcendence
    env_file: .env
    init: true
    restart: always
  api_gateway:
    container_name: api_gateway
    build: ./micro_services/api_gateway
    volumes:
      - api_gateway_db_volume:/database:rw
      - static_data_volume:/static:rw
    networks:
      - ft_transcendence
    restart: always
  user_manager:
    container_name: user_manager
    build: ./micro_services/user_manager
    volumes:
      - user_manager_db_volume:/database:rw
      - static_data_volume:/static:rw
    networks:
      - ft_transcendence
    restart: always
  friends_manager:
    container_name: friends_manager
    build: ./micro_services/friends_manager
    volumes:
      - friends_manager_db_volume:/database:rw
    networks:
      - ft_transcendence
    restart: always
  notifications:
    container_name: notifications
    build: ./micro_services/notifications
    volumes:
      - notifications_db_volume:/database:rw
    networks:
      - ft_transcendence
    restart: always
  leaderboard:
    container_name: leaderboard
    build: ./micro_services/leaderboard
    volumes:
      - leaderboard_db_volume:/database:rw
    networks:
      - ft_transcendence
    restart: always
  match_manager:
    container_name: match_manager
    build: ./micro_services/match_manager
    volumes:
      - match_manager_db_volume:/database:rw
    networks:
      - ft_transcendence
    restart: always
  frontend:
    container_name: frontend
    build: ./front_end
    networks:
      - ft_transcendence
    init: true
    restart: always
    # for developement
    volumes:
      - ./front_end/app:/app:rw

networks:
  ft_transcendence:
    name: ft_transcendence
    driver: bridge

volumes:
  api_gateway_db_volume:
    name: api_gateway_db_volume
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${HOME}/docker_volumes/api_gateway_db_volume"
  user_manager_db_volume:
    name: user_manager_db_volume
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${HOME}/docker_volumes/user_manager_db_volume"
  friends_manager_db_volume:
    name: friends_manager_db_volume
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${HOME}/docker_volumes/friends_manager_db_volume"
  notifications_db_volume:
    name: notifications_db_volume
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${HOME}/docker_volumes/notifications_db_volume"
  leaderboard_db_volume:
    name: leaderboard_db_volume
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${HOME}/docker_volumes/leaderboard_db_volume"
  match_manager_db_volume:
    name: match_manager_db_volume
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${HOME}/docker_volumes/match_manager_db_volume"
  static_data_volume:
    name: static_data_volume
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${HOME}/docker_volumes/static_data_volume"
  rabbit_mq_log_volume:
    name: rabbit_mq_log_volume
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${HOME}/docker_volumes/rabbit_mq_log_volume"
  vault_storage:
    name: vault_storage
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${HOME}/docker_volumes/vault_storage"
