# No need to pass cookie as REST client support cookies (optionaly you can pass them only if you connect with OAuth via browser or if you disable REST client cookies)
# install REST Client vscode extension. https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# Here will be tests for all upcoming routes use this as a guide to better understand the api behaviour


# GET the discovery document of the server: (No authorization required)
# READ THIS DOCUMENT FOR A DETAILED DESCRIPTION OF EACH ROUTE
GET https://server.transcendence.fr/.well-known/discovery





###### START GOOGLE OAUTH TESTs (No authorization required) ######

# GET a random state_code for OAuth flow:
GET https://server.transcendence.fr/OAuth/state

###

# GET user info:
GET https://server.transcendence.fr/user/info?uid=
# Cookie: jwt={{jwt_token}}

###### END GOOGLE OAUTH TESTs ######





###### START USER/PWD TESTs (No authorization required) ######

# Signup standard user:
POST https://server.transcendence.fr/user/signup
Content-Type: multipart/form-data; boundary=boundary13132121321H_4zdzdz90dlzkn

--boundary13132121321H_4zdzdz90dlzkn
Content-Disposition: form-data; name="username"

msitni
--boundary13132121321H_4zdzdz90dlzkn
Content-Disposition: form-data; name="password"

very_hard_password
--boundary13132121321H_4zdzdz90dlzkn--

###

# Signin standard user:
POST https://server.transcendence.fr/user/signin
Content-Type: multipart/form-data; boundary=boundary13132121321H_4zdzdz90dlzkn

--boundary13132121321H_4zdzdz90dlzkn
Content-Disposition: form-data; name="username"

msitni
--boundary13132121321H_4zdzdz90dlzkn
Content-Disposition: form-data; name="password"

very_hard_password
--boundary13132121321H_4zdzdz90dlzkn--

###### END USER/PWD TESTs ######





###### START USER MANAGEMENT TESTs (Authorization required) ######

# GET current logged user info uid alias:
GET https://server.transcendence.fr/user/info?uid=me
# Cookie: jwt={{jwt_token}}

###

# Change current logged user info:
POST https://server.transcendence.fr/user/info
# Cookie: jwt={{jwt_token}}
Content-Type: multipart/form-data; boundary=boundary13132121321H_4zdzdz90dlzkn

--boundary13132121321H_4zdzdz90dlzkn
Content-Disposition: form-data; name="username"

msitni
--boundary13132121321H_4zdzdz90dlzkn
Content-Disposition: form-data; name="bio"

hey everyone this is my new bio.
--boundary13132121321H_4zdzdz90dlzkn--

###

# Delete user's profile picture
DELETE https://server.transcendence.fr/user/remove_picture
# Cookie: jwt={{jwt_token}}

###### END USER MANAGEMENT TESTs ######





###### START MISC TESTs ######

# Check if username is available: (No authorization required)
GET https://server.transcendence.fr/user/namecheck?username=simbolic

###

###### END MISC TESTs ######




###### START FRIENDS SYSTEM TESTs (Authorization required) ######

# Get current user friends list
GET https://server.transcendence.fr/friends
# Cookie: jwt={{jwt_token}}

###

# Get current user friends requests
GET https://server.transcendence.fr/friends/requests
# Cookie: jwt={{jwt_token}}

###

# Send a friend request
POST https://server.transcendence.fr/friends/request?uid=
# Cookie: jwt={{jwt_token}}

###

# Accept a friend request
POST https://server.transcendence.fr/friends/accept?uid=
# Cookie: jwt={{jwt_token}}

###

# Deny a friend request
POST https://server.transcendence.fr/friends/deny?uid=
# Cookie: jwt={{jwt_token}}

###

# Remove a friend
POST https://server.transcendence.fr/friends/remove?uid=
# Cookie: jwt={{jwt_token}}

###

###### END FRIENDS SYSTEM TESTs ######




@jwt_token = put_token_here_and_uncomment_cookie_header_and_disable_cookie_feature_from_settings