# install REST Client vscode extension. https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# Here will be tests for all upcoming routes use this as a guide to better understand the api behaviour
# No need to pass cookie as REST client support cookies (optionaly you can pass them only if you connect with OAuth via browser)

# GET the discovery document of the server:
GET https://server.transcendence.fr/.well-known/discovery

###

# GET a random state_code for OAuth flow:
GET https://server.transcendence.fr/OAuth/state

###

# GET user info:
GET https://server.transcendence.fr/user/info?uid=105404925440430836662

###

# GET current logged user info uid alias:
GET https://server.transcendence.fr/user/info?uid=me

###

# Check if display name is available:
GET https://server.transcendence.fr/user/namecheck?username=ahmed

###

# Signup standard user:
POST https://server.transcendence.fr/user/signup
Content-Type: multipart/form-data; boundary=boundary13132121321H_4zdzdz90dlzkn

--boundary13132121321H_4zdzdz90dlzkn
Content-Disposition: form-data; name="username"

Ahmedssxssqa14
--boundary13132121321H_4zdzdz90dlzkn
Content-Disposition: form-data; name="password"

Ahmed123456
--boundary13132121321H_4zdzdz90dlzkn--

###

# Signin standard user:
POST https://server.transcendence.fr/user/signin
Content-Type: multipart/form-data; boundary=boundary13132121321H_4zdzdz90dlzkn

--boundary13132121321H_4zdzdz90dlzkn
Content-Disposition: form-data; name="username"

Ahmedssxssqa14
--boundary13132121321H_4zdzdz90dlzkn
Content-Disposition: form-data; name="password"

Ahmed123456
--boundary13132121321H_4zdzdz90dlzkn--

###

# Change current logged user info:
POST https://server.transcendence.fr/user/info
Content-Type: multipart/form-data; boundary=boundary13132121321H_4zdzdz90dlzkn

--boundary13132121321H_4zdzdz90dlzkn
Content-Disposition: form-data; name="username"

new_username
--boundary13132121321H_4zdzdz90dlzkn
Content-Disposition: form-data; name="bio"

hey everyone this is my new bio.
--boundary13132121321H_4zdzdz90dlzkn--

###

# Delete user's profile picture
DELETE https://server.transcendence.fr/user/remove_picture

###